M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Fr 03 Feb 2023 15:07:50 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-03T15:07:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0610
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0827
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X4.408Y-3.07
X4.538Y-3.115
X4.718Y-3.115
X4.853Y-3.065
T2
X4.64Y-3.31
T3
X4.26Y-1.9
X5.0Y-1.9
T4
X4.06Y-2.06
X4.8Y-3.55
X5.2Y-2.06
T0
M30
