M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Fr 03 Feb 2023 15:07:50 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-03T15:07:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1772
%
G90
G05
T1
X4.441Y-1.905
X4.819Y-1.905
T2
X4.44Y-2.58
X4.46Y-3.78
X4.4628Y-3.9884
X4.8Y-3.78
X4.8028Y-3.9884
X4.814Y-2.58
T3
X4.633Y-1.95
T0
M30
